import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import createPdf from "../utils/pdf/createPDF";

const Home: NextPage = () => {
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    const newDate = new Date(startDate);
    console.log(newDate);
    // newDate = newDate.;
    console.log(newDate);
    console.log(startDate);
    console.log(endDate);
    // createPdf(startDate, endDate);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <label htmlFor="start-date">Start Date</label>
          <input
            id="start-date"
            type="date"
            onChange={(e) => setStartDate(e.target.value)}
          />
          <label htmlFor="end-date">End Date</label>
          <input
            id="end-date"
            type="date"
            onChange={(e) => setEndDate(e.target.value)}
          />
          <button type="submit">Create PDF</button>
        </form>
      </main>
    </>
  );
};

export default Home;
