import type { NextPage } from "next";
import Head from "next/head";
import createPdf from "../utils/pdf/createPDF";

const Home: NextPage = () => {
  const addPdf = () => {
    createPdf();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <button onClick={addPdf}>Create PDF</button>
      </main>
    </>
  );
};

export default Home;
